name: Elkeid_plugin_scanner

on:
  push:
    branches:
    - main
    - 1.9/scanner

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Scanner
      uses: docker/build-push-action@v3
      with:
        file: plugins/scanner/docker/Dockerfile.aarch64
        load: true
        tags: elkeid/scanner_aarch64:latest
        context: .
        platforms: linux/arm64

    - name: Extract Scanner
      id: extract-scanner
      uses: shrink/actions-docker-extract@v1
      with:
        image: elkeid/scanner_aarch64:latest
        path: /Elkeid/plugins/scanner/output/.

    - name: Upload Scanner
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.extract-scanner.outputs.destination }}
        name: scanner